name: Build deb package

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, "${{ matrix.archconfig }}", high-mem ]
    strategy:
      matrix:
        archconfig: [ x86_64, aarch64 ]
        build_type: [ Debug, Release ]
      fail-fast: false
    steps:
    - name: Cleanup previous jobs
      run: |
        echo "Cleaning up previous runs"
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive


    - name: Find SHA
      run: |
        # If we are in a PR, use the name of the branch that we want to merge,
        # otherwise "main" or tag name
        if [[ "${{github.event.pull_request.head.sha}}" != "" ]]
        then
          echo "ARTIFACT_SHA=$(echo ${{github.event.pull_request.head.ref}})" >> $GITHUB_ENV
        else
          echo "ARTIFACT_SHA=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
        fi

    - name: Install deps
      id: install-deps
      run: |
        sudo apt update
        sudo apt install -y cmake libclang-dev

    - name: Build project
      id: build_plugin
      run: |
        mkdir -p build_${{matrix.build_type}}
        cd build_${{matrix.build_type}}
        cmake ${{github.workspace}} \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build . --config ${{matrix.build_type}} && \
        cpack 

    - name: Get package name
      shell: bash
      id: get_package
      run: |
        echo ::set-output name=NAME::$(basename build_${{ matrix.build_type }}/vaccelrt-*.deb)

    - name: Upload artifact to s3
      uses: cloudkernels/minio-upload@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: build_${{ matrix.build_type }}/${{ steps.get_package.outputs.NAME }}
        remote-path: nbfc-assets/github/vaccelrt/plugins/serrano-gpu/${{ env.ARTIFACT_SHA }}/${{ matrix.archconfig }}/${{ matrix.build_type }}-deb/
        policy: 1
    - name: Clean-up
      run: sudo rm -rf build_${{ matrix.build_type }}
